name: 'Movie_dbt_project'
version: '1.0.0'

profile: 'Movie_dbt_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  Movie_dbt_project:
    silver:
      +schema: silver         # ✅ This applies to ALL models in models/
      +materialized: view     # ✅ Ensure default is 'view' for all
    gold:
      +schema: gold         # ✅ This applies to ALL models in models/
      +materialized: table    # ✅ Ensure default is 'view' for all
